---
# This playbook deploys the whole application stack in this site.
- hosts: all

- name: preparing Server with dependency
  vars_files:
    - group_vars/all
    - group_vars/Server
  remote_user: ubuntu

  roles:
    - Server


- name: configure and deploy the webservers and application code
  remote_user: ubuntu
  vars_files:
        - group_vars/all
        - group_vars/django

  roles:
    - Django
