---    
  - name: Clone/pull project repo
      git : repo={{ project_repo }} dest={{ install_root }}/{{ project_name }} accept_hostkey=yes
      notify:
        - restart gunicorn
  

      - name: install python packages
        pip: requirements={{ install_root }}/{{ project_name }}/requirements.txt
        notify:
        - restart gunicorn
  

      - name: copy nginx config
        template: src=nginx.j2 dest=/etc/nginx/sites-enabled/{{ project_name }}.conf
        notify:
        - restart nginx
  


      - name: remove default nginx site
        file: path=/etc/nginx/sites-enabled/default state=absent

      - name: Make executable
         file: path=/srv/trydjango/manage.py mode=0777

      - name: django migrate
        django_manage: command=migrate app_path={{ install_root }}/{{ project_name }} pythonpath={{ pythonpath }}
  


      - name: django collectstatic
        django_manage: command=collectstatic app_path={{ install_root }}/{{ project_name }} pythonpath={{ pythonpath }}
  

      - name: copy gunicorn config
        template: src=gunicorn.j2 dest=/etc/init/gunicorn.conf
        notify:
        - restart gunicorn
  

      - name: make sure nginx server is running
        service: name=nginx state=started enabled=yes
  

      - name: make sure gunicorn server is running
        service: name=gunicorn state=started enabled=yes
  
  

